apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2021-12-29T04:56:11Z"
  name: secret-manager
  namespace: blue
  resourceVersion: "31950"
  uid: 4f40638e-0e8b-4e6e-9594-94173f08a7d0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-manager
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: jane
