apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2021-12-29T04:47:03Z"
  name: secret-manager
  namespace: red
  resourceVersion: "31192"
  uid: 8889b59c-fefb-455a-8d91-0169531ee94e
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
