apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2021-12-29T04:54:40Z"
  name: secret-manager
  namespace: blue
  resourceVersion: "31823"
  uid: 0be1e01a-5168-4f66-a872-603f94a5da70
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
